services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_OIDC_ISSUER=http://localhost:8081/realms/practice-management
        - VITE_OIDC_CLIENT_ID=practice-management-client
        - VITE_OIDC_REDIRECT_URI=http://localhost:5173/callback
        - VITE_OIDC_SCOPE=openid profile email
        - VITE_OIDC_RESPONSE_TYPE=code
        - VITE_ENABLE_SKINS=true
        - VITE_USER_CONFIG=http://localhost:8081/admin/practice-management/console
    container_name: practice-managment-app
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_OIDC_ISSUER=http://localhost:8081/realms/practice-management
      - VITE_OIDC_CLIENT_ID=practice-management-client
      - VITE_OIDC_REDIRECT_URI=http://localhost:5173/callback
      - VITE_OIDC_SCOPE=openid profile email
      - VITE_OIDC_RESPONSE_TYPE=code
      - VITE_ENABLE_SKINS=true
      - VITE_USER_CONFIG=http://localhost:8081/admin/practice-management/console
    depends_on:
      - keycloak
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: practice-managment-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      - --features=scripts
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: practice-managment-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
